# Generated by Django 5.0.6 on 2024-05-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
